ethersphere/beekeeper

- cmd/beekeeper/cmd/check_peercount.go
- pkg/check/peercount.go
You have to provide custom url-template for github actions and local testing 
If url-template is provided namespace is not needed
> Add hidden option url-template

- cmd/beekeeper/cmd/check_fileretrieval.go
- cmd/beekeeper/cmd/check_pingpong.go
- cmd/beekeeper/cmd/check_pushsync.go
- cmd/beekeeper/cmd/check_retrieval.go
- pkg/dynamick8s/dynamick8s.go
@svetomir this first has to be tested
> add support for incluster client config

- cmd/beekeeper/cmd/check.go
- cmd/beekeeper/cmd/check_chunkrepair.go
- pkg/bee/chunk.go
- pkg/bee/node.go
- pkg/beeclient/api/api.go
- pkg/beeclient/api/chunks.go
- pkg/beeclient/api/errors.go
- pkg/beeclient/debugapi/chunks.go
- pkg/beeclient/debugapi/debugapi.go
- pkg/check/chunkrepair/chunkrepair.go
- pkg/check/chunkrepair/metrics.go
This PR will add the support for testing chunk repair alias global pinning in the cluster. It should do the following
- Add chunk remove api support
- create command for chunk reapir
- create the check for chunk repair
- test in the cluster
> Chunk repair testcase support

- pkg/bee/node.go
- pkg/check/localpinning/localpinning.go
- pkg/check/pullsync/pullsync.go
some errors have been observed on these tests. this is an attempt to reduce test flakiness.
> retry localpinning download and pullsync test

- pkg/check/chunkrepair/chunkrepair.go
A small change to return the error on failure.
> Return the error for chunkrepair chunk recovery not triggered

- pkg/check/gc/chunk_notfound.go
> add more chunks in gc check

- pkg/check/pullsync/pullsync.go
this PR changes pullsync integration tests to check only for NN replication.
> pullsync: check only NN replication

- go.sum
- pkg/check/kademlia/dynamic.go
- pkg/check/kademlia/kademlia.go
@janos @svetomir I think this is something we can start with and iterate on. Would be happy for you feedback.
ref https://github.com/ethersphere/bee/issues/1121
> adjust dynamic kademlia check

- cmd/beekeeper/cmd/check_kademlia.go
- cmd/beekeeper/cmd/check_pingpong.go
- pkg/bee/nodegroup.go
- pkg/check/chunkrepair/chunkrepair.go
- pkg/check/fileretrieval/fileretrieval.go
- pkg/check/kademlia/dynamic.go
- pkg/check/pingpong/dynamic.go
- pkg/check/pingpong/pingpong.go
- pkg/k8s/bee/node.go
This is PR with dynamic pingpong test and few improvements I found quite useful for dynamic checks in general.
I tested functionality and it works fine, but please double check it. :)
There is a lot of code duplication between this check and dynamic kademlia, but you may disregard it for now. A new issue is open for this and it will go through a separate PR.
> Dynamicpingpong

- pkg/bee/chunk.go
- pkg/bee/client.go
- pkg/beeclient/api/chunks.go
- pkg/check/chunkrepair/chunkrepair.go
- pkg/check/gc/chunk_notfound.go
- pkg/check/localpinning/chunk_found.go
- pkg/check/pullsync/pullsync.go
- pkg/check/pushsync/pushsync.go
- pkg/check/retrieval/retrieval.go
needed for https://github.com/ethersphere/bee/pull/1143
> bee, check: accommodate for chunk api changes

- pkg/check/settlements/settlements.go
PR resolves this issue https://github.com/ethersphere/beekeeper/issues/99
> Fail if settlments haven't happend

- cmd/beekeeper/cmd/check_settlements.go
- pkg/check/settlements/settlements.go
> require only one settlement for each upload

- cmd/beekeeper/cmd/check_chunkrepair.go
- pkg/bee/client.go
- pkg/check/chunkrepair/chunkrepair.go
- pkg/check/localpinning/remote_chunks_found.go
based on https://github.com/ethersphere/bee/issues/1125
> Remove RemoveChunkWithAddress

- install.sh
Add `install.sh` script to enable easy installation
specific version
```
curl -s https://raw.githubusercontent.com/ethersphere/beekeeper/master/install.sh | TAG=v0.5.3 bash
```
latest 
```
curl -s https://raw.githubusercontent.com/ethersphere/beekeeper/master/install.sh | bash
```
> add install.sh script

- pkg/bee/cluster.go
- pkg/check/balances/balances.go
- pkg/check/gc/chunk_notfound.go
- pkg/check/gc/reserve.go
Please review if these changes will break gc check.
> Support multi node-groups in gc check

- pkg/bee/client.go
- pkg/bee/nodegroup.go
- pkg/beeclient/debugapi/node.go
- pkg/beeclient/debugapi/postage.go
- pkg/bigint/bigint.go
- pkg/bigint/bigint_test.go
- version.go
This PR is newer version of https://github.com/ethersphere/beekeeper/pull/148.
Description is written by @AuHau and copied from https://github.com/ethersphere/beekeeper/pull/148:
This PR tackles the Bee BigInt serialization PR (ethersphere/bee-js#290).
It compiles but I did not manage to actually run it as I am running on macOS and bee-local has problems with macOS :-( Could somebody please verify it functions as expected?
Also I have duplicated the bigint package from Bee as I don't really now how to include it from package as in the Bee it is not yet merged into master, but in order for it to be merged Beekeeper's tests needs to be working. Once it is merged then I can rework it to use the package directly from Bee.
> Big int serialization

- config/config.yaml
- config/local.yaml
adjust thresholds for "negotiate cheques"
> adjust thresholds

- config/local.yaml
use the default bee thresholds in ci tests
> use default thresholds for tests

- config/config.yaml
- config/local.yaml
- pkg/bee/client.go
- pkg/bee/postage.go
- pkg/beeclient/debugapi/postage.go
- pkg/check/balances/balances.go
- pkg/check/chunkrepair/chunkrepair.go
- pkg/check/fileretrieval/fileretrieval.go
- pkg/check/gc/reserve.go
- pkg/check/pullsync/pullsync.go
- pkg/config/check.go
This PR:
- rewrites the gc tests to thoroughly test the new reserve logic
- adds significant documentation to these tests as they are complex and verbose
> rework gc integration tests

- pkg/check/pushsync/check_lightnode.go
Adds extra sleeping and retries to upload and download calls and uses a single batch for per node.
> lightnode fix

- pkg/check/authenticated/authenticate.go
- pkg/test/auth.go
- pkg/test/case.go
- pkg/test/funcs.go
- pkg/test/node.go
- version.go
It also contains an attempt to a fluent API design (collection->filter->map on line 69)
> fix: high level API for auth check

- cmd/beekeeper/cmd/print.go
- pkg/bee/client.go
- pkg/bee/debugapi/node.go
- pkg/check/kademlia/kademlia.go
- pkg/check/pullsync/pullsync.go
the contract broke a while ago and no one noticed. we need integration tests for the api responses from bee @svetomir
> fix: broken topology contract

- cmd/beekeeper/cmd/print.go
Removed logger from print function because it's not needed, just reverted to previous state and added new fuction to print all node names
> chore: remove logger from print fuction

- config/local.yaml
- pkg/bee/client.go
- pkg/bee/debugapi/postage.go
- pkg/check/postage/postage.go
Topup amount increased from initial amount to allow postage-new-depth to increase.
> fix: ci topup option fix

- config/config.yaml
- config/local.yaml
- config/testnet-giant.yaml
- config/testnet.yaml
- pkg/bee/api/auth.go
- pkg/bee/client.go
- pkg/bee/debugapi/node.go
- pkg/check/settlements/settlements.go
- pkg/orchestration/cluster.go
- pkg/orchestration/k8s/cluster.go
- pkg/orchestration/k8s/nodegroup.go
- pkg/orchestration/nodegroup.go
Contains combined changes from #231 #225 #205 and guaranteed wait times between upload and download for settlement tests to allow longer wait period when uploading from the light node in the test
> feat: Accounting related changes 

- pkg/config/bee.go
- pkg/orchestration/k8s/helpers.go
- pkg/orchestration/node.go
add missing addresses and flag
> fix: add missing contract addresses

- config/local.yaml
- pkg/check/pss/pss.go
- pkg/config/check.go
- pkg/orchestration/k8s/cluster.go
beekeeper updates to match changes for https://github.com/ethersphere/bee/pull/3616
> feat: make bootnode as lightnode

- pkg/check/pss/pss.go
minor cosmetics for previous PR https://github.com/ethersphere/beekeeper/pull/299
> chore: pss check cosmetics

- config/local.yaml
- pkg/config/bee.go
- pkg/orchestration/k8s/helpers.go
- pkg/orchestration/node.go
> fix: postage stamp start block

- pkg/bee/api/auth.go
- pkg/bee/client.go
- pkg/bee/debugapi/stake.go
- pkg/check/stake/stake.go
> feat: withdraw stake

- pkg/check/settlements/settlements.go
> chore: run settlements check on fullnodes only

- config/config.yaml
- config/local.yaml
- config/testnet-giant.yaml
- config/testnet.yaml
- pkg/config/bee.go
- pkg/orchestration/k8s/helpers.go
- pkg/orchestration/k8s/nodegroup.go
- pkg/orchestration/node.go
Remove obsolete bee config options. Bee will now fail if unknown options are inside config https://github.com/ethersphere/bee/pull/3782
> fix: fix bee config options

- pkg/check/smoke/smoke.go
When a data mismatch occurs during a smoke test run, the download is retried.
> fix(smoke): retry retrieval on data mismatch

- config/config.yaml
- config/local.yaml
- pkg/check/longavailability/longavailability.go
- pkg/check/longavailability/metrics.go
- pkg/config/check.go
Adds a check for long availability. It receives a list of references and tries to download them.
> feat: check long availability

- go.mod
- go.sum
- version.go
bump beekeeper version to 0.15.8 and update 2 other deps in go.mod
> chore: bump version to 0.15.8

- config/local.yaml
With `bee-localchain:0.9.0-rc3` contracts are changed, this PR fixes values
> chore: change swap-factory-address and price-oracle-address

- cmd/beekeeper/cmd/cluster.go
- config/config.yaml
- config/local.yaml
- config/testnet-giant.yaml
- config/testnet.yaml
- pkg/config/bee.go
- pkg/config/cluster.go
- pkg/config/nodegroup.go
- pkg/orchestration/k8s/helpers.go
- pkg/orchestration/k8s/node.go
- pkg/orchestration/k8s/node_orchestrator.go
- pkg/orchestration/k8s/nodegroup.go
- pkg/orchestration/node.go
- pkg/orchestration/nodegroup.go
Removing clef references also in [Bee](https://github.com/ethersphere/bee/pull/4812)
> chore: remove clef references

- cmd/beekeeper/cmd/cluster.go
- cmd/beekeeper/cmd/cmd.go
- config/beekeeper-local.yaml
- config/public-testnet.yaml
- config/staging.yaml
This will allow specifying directory in the repository with configurations.
> feat: add 'config-git-dir' global option

- config/config.yaml
- config/local.yaml
- pkg/check/smoke/smoke.go
Sleep before the next iteration of the smoke check
> chore: sleep before next iteration

- config/config.yaml
- config/local.yaml
- config/public-testnet.yaml
- pkg/check/gsoc/gsoc.go
- pkg/check/pss/pss.go
- pkg/websocket/websocket.go
- pkg/wslistener/wslistener.go
1. Add retry for expected pss messages
2. Refactor the WebSocket listener to not read on a closed connection
> fix: more reliable pss and gsoc

- cmd/beekeeper/cmd/check.go
- config/local.yaml
- pkg/scheduler/duration.go
Use timeout handler if timeout is 0 then no timeout should happen, also for duration executor order check if context is done to not have panic when sending on closed channel.
> fix: improve duration executor order and use timeout handler for checks

- pkg/orchestration/k8s/cluster.go
> chore: fix comment

- README.md
- cmd/beekeeper/cmd/check.go
- cmd/beekeeper/cmd/create.go
- cmd/beekeeper/cmd/delete.go
- cmd/beekeeper/cmd/fund.go
- cmd/beekeeper/cmd/node_funder.go
- cmd/beekeeper/cmd/operator.go
- cmd/beekeeper/cmd/print.go
- cmd/beekeeper/cmd/restart.go
- cmd/beekeeper/cmd/simulate.go
- cmd/beekeeper/cmd/stamper.go
- cmd/beekeeper/cmd/version.go
This PR improves the Beekeeper CLI by standardizing command descriptions and adding comprehensive help text. All commands now have consistent formatting and detailed explanations that guide users through functionality.
> docs: enhance command long descriptions for clarity

- README.md
This PR improves the Beekeeper README by adding a Quick Start guide and enhancing documentation quality.
- **Added Quick Start section** with local development setup steps
- **Enhanced installation instructions** for macOS/Linux/Windows
- **Improved code formatting** and markdown styling
- **Fixed typos and grammar** throughout the document
- **Better configuration documentation** with clearer parameter descriptions
> docs: enhance README with better formatting and examples
