README.md, cmd/beekeeper/cmd/check.go, cmd/beekeeper/cmd/check_manifest.go, pkg/bee/file.go, pkg/bee/node.go, pkg/beeclient/api/api.go, pkg/beeclient/api/dirs.go, pkg/check/manifest/manifest.go
It generates number of files and creates TAR archive from them.
This archive is uploaded and each file is checked if it is valid through `bzz` endpoint, thus testing manifests in `bee` project.
=> Add support for checking manifest functionality

pkg/bee/node.go, pkg/beeclient/api/files.go, pkg/check/balances/balances.go, pkg/check/fileretrieval/fileretrieval.go, pkg/check/fileretrievaldynamic/fileretrievaldynamic.go, pkg/check/localpinning/localpinning.go
This PR enables usage of the `Swarm-Pin` header for uploads in order to upload and pin on local pinning tests.
It removes all sorts of checks that were done since they simply do not factor the fact that we need to pin multiple chunks, and we need to list all pinned chunks which is not possible right now, since paging is not implemented and listing pinned chunks simply cannot account for all of the pinned chunks. Thus, an exhaustive check cannot be made at this point. Once paging is done on listing pinned chunks we can implement verification of pinned chunks and also do unpinning tests.
Closes https://github.com/ethersphere/bee/issues/248.
=> baseline local pinning tests

pkg/check/manifest/manifest.go
This PR addresses some of the edge cases which make manifest check flaky.
There is also a one log message corrected.
The retry counter is never reset, and eventually a file download fails without any retry. The retry is good to have because of the unknown time of syncing.
Test fails with manifest not found if the path length is zero by handling empty path without the manifest metadata.
fixes: https://github.com/ethersphere/bee/issues/848
=> Manifest check edge cases fixes

cmd/beekeeper/cmd/check_pushsync.go, pkg/bee/node.go, pkg/beeclient/api/api.go, pkg/beeclient/api/files.go, pkg/beeclient/api/tags.go, pkg/check/pushsync/pushsync.go
Introduces additional check for 'pushsync' that uploads files to the node (with tag configured), and then checks if counters from tag are expected.
This change also adds `TagsService`, and accompanying functions, to allow using that API.
From the tag counters, `split` value is used as expected number of chunks that need to be pushed, `sent` value is used to see how many chunks have been pushed so far, and `seen` value as number of chunks that are left on the uploading node, and not synced (due to the distribution of chunks through the cluster). For this `seen` value, I was not aware, but have observed on last testing session (generally was always `0`).
In the 'normal' operation, these numbers should usually match, otherwise it might indicate there is some problem.
These changes have been …
=> Add pushsync check for files using tags

pkg/bee/chunk.go, pkg/check/pullsync/pullsync.go, pkg/check/pushsync/pushsync.go, pkg/check/retrieval/retrieval.go
Identified a bug where we were uploading a chunk to the bytes api. Because when generating the chunk, the span is appended to the random generated bytes, the hash which was returned from the bytes API was different than the hash generated in the beekeeper tests, since bmt hash is calculated without the span in the actual data being hashed, and the bytes api treated the span data that was appended to the data as actual data, not span data, resulting in a different hash. So actually the data chunk that was uploaded had a different hash, but the checks inside the actual tests use `chunk.ClosestNode`, which correlates to the correct hash (which wasn't in fact uploaded correctly), resulting in incorrect assumptions, and chunks which are never found where they are supposed to be.
=> Fix flaky tests

cmd/beekeeper/cmd/check.go, cmd/beekeeper/cmd/check_localpinning_remote.go, pkg/bee/node.go, pkg/beeclient/api/pinning.go, pkg/beeclient/debugapi/node.go, pkg/check/chunkrepair/chunkrepair.go, pkg/check/localpinning/bytes_found.go, pkg/check/localpinning/chunk_found.go, pkg/check/localpinning/remote_chunks_found.go
relates to: [ethersphere/bee#571](https://github.com/ethersphere/bee/issues/571)
Adds `pin-remote` check that performs pinning of bytes upload and then checks all those chunks are present locally using debug API.
One partly unfortunate thing is that because of how the Bee operates, if there is too few nodes in the topology, it is possible that all of them will replicate all chunks between themselves. As an attempt to "combat" this, few changes were made:
1. number of chunks that are being generated for upload was increased to `8000`
2. timeout to wait for chunks replication is set to `15` seconds
3. there is "verification" step that queries each node for expected chunks, and only on the nodes that do not have all the chunks does it perform pinning
- initial idea was to return an error if …
=> Add test for pinning that fetches remote chunks

pkg/check/kademlia/dynamic.go
fixes a bug where nodes would check connection to themselves since it satisfies the original check in `nodesInDepth`
=> dynamic kademlia: dont check self

cmd/beekeeper/cmd/check_pushsync.go, pkg/check/pushsync/check_chunks.go
`RetryDelay` is used in pushsync-files but not in pushsync-chunks. This PR uses it in both cases.
=> make delay in pushsync-chunks configurable

pkg/check/pushsync/check_chunks.go, pkg/check/pushsync/pushsync.go
It is a bit difficult to trace what's happening in the pushsync tests, I therefore make some changes to print the culprit chunk addresses and node names in tests, plus adding a few intermediate log lines, to outline uploader node explicitly, and closest node names, etc
=> pushsync: improve logging

cmd/beekeeper/cmd/check.go, cmd/beekeeper/cmd/check_cashout.go, pkg/bee/client.go, pkg/beeclient/debugapi/node.go, pkg/check/cashout/cashout.go, scripts/suite.sh
This adds a check to beekeeper to test cashout functionality which currently has no coverage in tests using an actual blockchain.
It cashes out all cheques with uncashed amounts and waits for the receipt to be available and verifies that the total balance of the node which cashes out does actually change (this is not guaranteed if the other node also has a cheque in the other direction with exactly the same amount but this should be incredibly unlikely). 
All cashout transactions happen in parallel (thus this is also testing the nonce manager) an it waits at most 50s for all of them to confirm (which should always be enough for the testing blockchain). If there are no cheques to cashout, the check simply passes without doing anything.
=> add a test for cashouts

pkg/check/retrieval/retrieval.go
client has been overridden with a different client, resulting in the tests breaking due to stamp issuer not found
=> fix retrieval test

cmd/beekeeper/cmd/check.go, cmd/beekeeper/cmd/simulate.go, config/config.yaml, pkg/config/bee.go, pkg/config/simulation.go, pkg/k8s/bee.go, pkg/k8s/bee/helpers.go, pkg/simulate/retrieval/metrics.go, pkg/simulate/retrieval/retrieval.go
This PR creates a chunk retrieval simulation, similar to the retrieval check where chunks are uploaded to nodes and downloaded to validate that they are retrievable.
The simulation is in form of a continuous set of uploads and downloads with configurable number of nodes, chunks per node and delay between uploads.
The result of the simulation are metrics beekeeper_simulation_retrieval_*.
There is no defined time for which the simulation is supposed to run. It runs until the context is canceled. In practice, until the beekeeper process is terminated.
=> retrieval simulation

pkg/simulate/retrieval/metrics.go, pkg/simulate/retrieval/retrieval.go
This PR changes the metrics label "cluster" to "run" which is unique up to the nano timestamp in order not to mix metrics on the same cluster between different simulation runs.
=> Set new metrics label run for retrieval simulation

pkg/check/gc/reserve.go
adding a missing sleep in the gc check that could prevent chunks from being synced and then GCd
=> fix: sleep in gc check

pkg/check/gc/reserve.go
this change is needed due to the upper bound check of the eviction target which was changed recently
=> fix: gc chunks number

pkg/check/fullconnectivity/fullconnectivity.go
I made a mistake when setting expected peer count: if a bootnode would be picked first it would set the expected peer count to 4, even if for bee nodes it should stay 2.
=> fix: wrong expect count

pkg/beeclient/api/api.go, pkg/beeclient/api/errors.go, pkg/beeclient/api/errors_test.go, pkg/beeclient/debugapi/debugapi.go, pkg/beeclient/debugapi/errors.go, pkg/beeclient/debugapi/errors_test.go, pkg/beeclient/debugapi/node.go
This PR changes how HTTP error responses are handled in `api` and `debugapi` packages. Bee sends a json-encoded body with `"message"` field which may contain some information about the error. It is sent for all responses, not just for the bad request and no `"errors"` field is sent. This PR adjusts the error handling to include additional information in the error message, to unify errors by their code, but does not deduplicate implementations into a single package, just adjusts similar code in both packages, as that should be a part of a different PR.
=> feat: propagate message from bee http error responses

config/config.yaml, config/local.yaml, pkg/bee/client.go, pkg/beeclient/debugapi/postage.go, pkg/check/postage/postage.go, pkg/config/check.go
- Create batch
- Top Up created batch
- Dilute batch
```shell
❯ beekeeper check --checks=postage --cluster-name=local
field GasPrice not set, using default value
field PostageLabel not set, using default value
node bootnode-0: created new batch id b650913341b03af0ebed9e45adc22e7c08cae988cd49e7950d30ad20e0585eec
node bootnode-0: topped up batch id b650913341b03af0ebed9e45adc22e7c08cae988cd49e7950d30ad20e0585eec
node bootnode-0: diluted batch id b650913341b03af0ebed9e45adc22e7c08cae988cd49e7950d30ad20e0585eec
❯ beekeeper check --checks=ci-postage --cluster-name=local
field GasPrice not set, using default value
field PostageLabel not set, using default value
node bootnode-0: created new batch id 9b1ad03897c0456ed02d846454e35759a493e3772c9e6f7f791a69467f82d2c8
node bootnode-0: topped up batch …
```
=> feat: add postage check

pkg/bee/api/api.go, pkg/bee/client.go, pkg/bee/debugapi/debugapi.go, pkg/check/manifest/manifest.go, pkg/config/config.go, pkg/swap/http.go
Replace deprecated `ioutil` package functions calls: https://golang.org/doc/go1.16#ioutil
=> refactor: replace deprecated ioutil package

pkg/orchestration/k8s/node.go, pkg/orchestration/k8s/nodegroup.go, pkg/orchestration/node.go, pkg/orchestration/utils/utils.go, pkg/swap/geth.go, pkg/swap/notset.go, pkg/swap/swap.go
* add support for
* internal signer bee nodes with predefined key without chequebook
* clef signer bee nodes with predefined key without chequebook
* clef signer bee nodes without predefined key without chequebook
* key generation has been updated to match the recent bee changes for V3 compatibility
=> add support for attesting existing and clef keys

cmd/beekeeper/main.go
OIDC auth plugin is enabled as described [here](https://github.com/liggitt/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/README.md#auth-plugins)
=> feat: enable oidc auth plugin

cmd/beekeeper/cmd/print.go
This option is needed for automatic collection of dump data from nodes when the Bee workflow fails.
`beekeeper print nodes --cluster-name local-dns` will print
```
bee-1
bee-0
light-0
light-1
restricted-0
```
and using this info we can easily collect all the data over api and debug api endpoints
=> chore: add print command to print all node names inside a cluster

Makefile, cmd/beekeeper/cmd/check.go, pkg/check/authenticated/authenticate.go, pkg/check/balances/balances.go, pkg/check/chunkrepair/chunkrepair.go, pkg/check/fileretrieval/fileretrieval.go, pkg/check/kademlia/kademlia.go, pkg/check/pingpong/pingpong.go, pkg/check/pushsync/check_lightnode.go, pkg/check/pushsync/pushsync.go, pkg/check/settlements/settlements.go
Enable (fix) running list of checks (ex: --checks=pingpong,retrieval)
Logger prints every running check: **running check: [checkName]**
Logger prints after every succesfull running check: **[checkName] check completed successfully**
Makefile: when run **make binary**, if OS is Windows  it will add **.exe** to executable file.
=> fix(checks): enable consecutive running checks and log printing

pkg/config/check.go, pkg/config/simulation.go, pkg/k8s/configmap/configmap_test.go, pkg/k8s/containers/containers_test.go, pkg/k8s/containers/ephermal_test.go, pkg/k8s/ingress/backend.go, pkg/k8s/ingress/client_test.go, pkg/k8s/ingress/ingress.go, pkg/k8s/ingress/rule.go, pkg/k8s/ingress/tls.go, pkg/k8s/k8s_test.go, pkg/k8s/namespace/namespace_test.go, pkg/k8s/persistentvolumeclaim/accessmode.go, pkg/k8s/persistentvolumeclaim/client_test.go, pkg/k8s/persistentvolumeclaim/persistentvolumeclaim.go, pkg/k8s/persistentvolumeclaim/persistentvolumeclaim_test.go, pkg/k8s/persistentvolumeclaim/selector.go, pkg/k8s/pod/client_test.go, pkg/k8s/pod/pod_test.go, pkg/k8s/secret/secret_test.go, pkg/k8s/service/client_test.go, pkg/k8s/serviceaccount/serviceaccount_test.go, pkg/k8s/statefulset/client_test.go, pkg/orchestration/k8s/node.go
All unit tests are moved to dedicated test packages, and code is modified accordingly. 
Quality of test cases is improved. 
Minor improvements are included in k8s packages  (init slice only when needed).
=> fix(k8s): test public methods only

pkg/k8s/customresource/ingressroute/client.go, pkg/k8s/customresource/ingressroute/ingressroute.go
IngressRoute client Set method updates IngressRoute or creates it if it does not exist
=> fix(k8s): add missing update option for ingress route

cmd/beekeeper/cmd/cmd.go, cmd/beekeeper/cmd/print.go, pkg/config/config.go
- add 'print config' option that dumps used configuration for cluster setup
- add log warnings when configuration is duplicated (in which case duplicated configuration is not taken into account)
=> feat: print config

mocks/k8s/statefulset.go, pkg/k8s/k8s.go, pkg/k8s/statefulset/client.go, pkg/k8s/statefulset/client_test.go, pkg/orchestration/k8s/node.go, pkg/orchestration/k8s/nodegroup.go, version.go
This pull request addresses an issue encountered when attempting to make a request to the k8s watch API to verify whether the statefulset contained sufficient ready replicas. Previously, when the context deadline was exceeded, the request would not return an error and would be retried indefinitely. The changes made in this pull request resolve the root cause of this issue.
=> fix: detect timeout with select in statefullset watch request

config/config.yaml, config/local.yaml, go.mod, go.sum, pkg/check/smoke/load.go, pkg/check/smoke/smoke.go
TImeout unresponsive upload/download.
=> fix(smoke): add timeout for upload and download

pkg/bee/client.go, pkg/bee/debugapi/postage.go, pkg/check/fileretrieval/fileretrieval.go, pkg/check/gc/reserve.go, pkg/check/manifest/manifest.go, pkg/check/postage/postage.go, pkg/check/pss/pss.go, pkg/check/pullsync/pullsync.go, pkg/check/pushsync/check_chunks.go, pkg/check/pushsync/check_lightnode.go, pkg/check/pushsync/pushsync.go, pkg/check/settlements/settlements.go, pkg/check/smoke/load.go, pkg/check/smoke/smoke.go, pkg/check/soc/soc.go, pkg/simulate/pushsync/pushsync.go, pkg/simulate/retrieval/retrieval.go, pkg/simulate/upload/upload.go, pkg/test/node.go
some tests rely on the batch being mutable
=> fix: turn off immutable header

go.mod, go.sum
This node-funder version will use mint instead of transfer function for localnet swarm token.
=> chore: bump node-funder to v0.0.3

config/config.yaml, config/local.yaml, pkg/bee/api/chunks.go, pkg/bee/client.go, pkg/check/datadurability/datadurability.go, pkg/check/datadurability/metrics.go, pkg/check/soc/soc.go, pkg/config/check.go, pkg/simulate/pushsync/pushsync.go, pkg/simulate/retrieval/retrieval.go, pkg/test/node.go
Adds data durability check
https://github.com/ethersphere/bee/issues/4475
=> feat: data durability check

pkg/check/redundancy/redundancy.go
Adds a non-happy path to the integration tests that checks that download fails if there's too much data loss.
=> feat: improve redundancy ci

README.md, cmd/beekeeper/cmd/node_funder.go, cmd/beekeeper/cmd/operator.go, config/config.yaml, config/local.yaml, config/testnet-giant.yaml, config/testnet.yaml, pkg/k8s/customresource/ingressroute/client.go, pkg/k8s/ingress/client.go, pkg/k8s/pod/client.go, pkg/operator/operator.go
Refactor: Extract label-selector as a flag with default `beekeeper.ethswarm.org/node-funder=true`.
- Introduced a flag to specify the label selector for K8S resources used by node-funder and operator.
- Default label selector set to `beekeeper.ethswarm.org/node-funder=true`.
- If the label selector is an empty string, no filtering is applied.
- The label selector works in conjunction with the namespace for more granular resource selection.
=> refactor: extract label-selector as a flag for node-funder and operator

pkg/config/bee.go, pkg/config/cluster.go, pkg/config/config.go, pkg/config/nodegroup.go
Fix for issue https://github.com/ethersphere/beekeeper/issues/149
=> fix(config): enable multiple inheritance

config/config.yaml, config/local.yaml, pkg/check/gsoc/gsoc.go, pkg/config/check.go, version.go
Adds gsoc check. See https://github.com/anythread/gsoc/blob/master/test/index.spec.ts
Summary:
- socs uploaded sequentially to `node1` should arrive `node2` on the subscribed web socket.
- socs uploaded in parallel to `node1` should also arrive `node2` on the subscribed web socket.
=> feat: gsoc check

cmd/beekeeper/cmd/check.go, config/config.yaml, config/public-testnet.yaml, pkg/check/pushsync/check_chunks.go, version.go
Config imrpoved and resolved issue with context timeout when multiple consecutive checks run. 
Now every run, child context is created.
=> fix(checks): enable multiple consecutive checks run for testnet

config/config.yaml, config/local.yaml, config/public-testnet.yaml, pkg/bee/api/api.go, pkg/bee/api/dirs.go, pkg/check/manifest/manifest.go, pkg/orchestration/cluster.go, pkg/orchestration/k8s/cluster.go
Uses feeds to test updates to a website
1. It creates a root feed manifest
2. To make an update to the feed, it uploads a tar website with some index.html and other files. Then uses this reference in the feed update.
3. It then tries to download the website via the root feed reference. It should resolve to the index.html
4. To update the website, we push another update to the feed with the new tar and then try to download it again via the root feed reference.
5. Lastly, it tries to download the other files in the website directly. e.g `b25c89a401d9f26811680476619a1eb4a4e189e614bc6161cbfd8b343214917b/assets/styles/styles.css`
=> feat: extend manifest integration test

cmd/beekeeper/cmd/check.go, pkg/check/runner.go
This commit improves the error handling in the check-runner by refining how errors are managed and reported:
- When a single check is executed and an error occurs, the error is returned immediately.
- When multiple checks are executed, every check is run regardless of errors. Each error is logged, and after all checks have run, a summary of all errors is returned.
=> fix(check-runner): improve error aggregation for multiple check failures

pkg/bee/client.go, pkg/check/gsoc/gsoc.go, pkg/orchestration/cluster.go, pkg/orchestration/k8s/cluster.go
A SOC can arrive at a node via push sync or pull sync.
With pull sync, you might not get all chunk versions because the newer version would have overridden the older one on the upstream node by the time you sync. 
This issue doesn't exist when the listener node receives the chunk via pushsync as it will receive the chunk immediately after it is pushed. Effectively receiving all versions.
This PR ensures that the listener gets the chunk via push sync and such, we can verify consistently that it receives all versions.
=> fix: gsoc via pushsync

pkg/check/runner.go, pkg/stamper/stamper.go
Idea of this PR is to improve output of errors, when multiple checks are executed.
Example output:
```
Error: CHECK_FAILED | 2/3 checks failed | Checks: ci-pss,pullsync | {"check":"ci-pss","time":"2025-03-03T13:11:27","error":"not implemented"} | {"check":"pullsync","time":"2025-03-03T13:11:27","error":"not implemented"}
```
=> fix(check): improve format of errors on multiple checks

pkg/check/gsoc/gsoc.go, pkg/check/pss/pss.go
Increase the depth for mining the soc addresses so that the listener node is picked more accurately when pushing out the chunk on the uploader.
Also increases the timeout to receive all messages.
=> fix: gsoc listner node selection

pkg/bee/api/feed.go, pkg/bee/client.go, pkg/check/feed/feed.go, pkg/check/manifest/manifest.go
Based on [Bee PR 5029](https://github.com/ethersphere/bee/pull/5029).
The feed wrapping is enforced to use in the `/bzz` requests instead of the old feed payload structure.
=> feat: feed wrapping

config/public-testnet.yaml, pkg/bee/api/api.go, pkg/bee/api/feed.go, pkg/check/manifest/manifest.go, pkg/check/smoke/load.go
The `pt-testnet-load` in the `beekeeper` namespace is configured with `--timeout=13h`. Previously, if the timeout elapsed, it would exit with an error. This change ensures that when the `duration` elapses, the check is considered successful, preventing an error exit.
=> chore: update config for pt-testnet-load

pkg/check/fullconnectivity/fullconnectivity.go, pkg/orchestration/k8s/cluster.go, pkg/orchestration/k8s/nodegroup.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use slices.Contains to simplify code
